/** chamber client-core shared faces: the instance unary client, the chamberBridge singleton, the control-plane REST client, the gateway dsh-runtime core (design 21 §5.2), and the page-owned restart→reload completion (design 18 §3.6 item 8).
 *
 * The `.` face is the production-consumed surface list, not a barrel: each module
 * contributes all of its types (`export type *`) plus an explicit named list of the
 * runtime values a production importer names. That list is the face
 * `verify-no-dead-exports` judges — a runtime value only a test needs is not a
 * public face: the test imports the module package-locally through its source path
 * (`../../../dsh-chamber-client-core/src/<mod>.ts`) instead, and a new production
 * consumer adds its face here in the same change. `archive-purge.ts` is NOT here: it
 * belongs to the sidebar package (moved to `src/client/archive-purge.ts`) because its
 * only production consumer is the sidebar. */

export type * from './instance-api.ts'
export type * from './instance-rpc-error.ts'
export { InstanceRpcError } from './instance-rpc-error.ts'
export { InstanceDomainMissingError, archiveSession, createHostDirectory, createSession, createWorkspace, deleteWorkspace, emptyAggregate, fetchInstanceSnapshot, forkSession, getInstanceClient, insertSessionBefore, insertWorkspaceBefore, isInstanceUnavailable, listHostDirectory, purgeArchivedSessions, releaseInstanceClient, renameSession, renameWorkspace, searchSessions, stopArchivedSubtree, stopSessionsForPurge } from './instance-api.ts'
export type * from './workspace-mutations.ts'
export { createWorkspaceForSource, deleteWorkspaceForSource, renameWorkspaceForSource } from './workspace-mutations.ts'
export type * from './wire-common.ts'
export { classifyGraphChannelFailure, isRecord, mintRpcId, postUnary } from './wire-common.ts'
export type * from './wire-error.ts'
export { throwIfInstanceUnavailable, wrapWireError } from './wire-error.ts'
export type * from './control-plane-client.ts'
export { controlPlaneUrl, post, request, toConnectionSummary, toLocalWriterDiagnosis } from './control-plane-client.ts'
export type * from './aggregate-store.ts'
export { SOURCE_PHASE_UNKNOWN, chamberBridge, isValidProducerSourceFingerprint } from './aggregate-store.ts'
export type * from './serving-gate.ts'
export { waitForSourceServing } from './serving-gate.ts'
export type * from './restart-window-reload.ts'
export { RESTART_RELOAD_BUDGET_MS, armLocalDshRestartCompletion, armWindowReloadWhenServed } from './restart-window-reload.ts'
export type * from './client-plugin-loader.ts'
export { BundleLoadTimeoutError, clientPluginRowOwner, dedupeCoveredRows, loadClientPluginRows } from './client-plugin-loader.ts'
export type * from './plugin-graph-recheck.ts'
export { isChannelClassDiagnostic, recheckPluginGraphDiagnostic } from './plugin-graph-recheck.ts'
export type * from './settings-shell.ts'
export { SETTINGS_SHELL_ENTRY_ID, SETTINGS_SHELL_SHADOW_PRIORITY, classifySettingsSeatOccupant, settingsSeatTakeoverMessage } from './settings-shell.ts'
export type * from './derive.ts'
export { BLANK_GHOST_GRACE_MS, SEARCH_QUERY_MAX_CODE_UNITS, armBlankGhost, basenameOf, canonicalPathKey, deriveArchivedSessions, deriveLocalSearchMatches, deriveServerWorkspaces, deriveUnread, gapSignature, groupArchivedRows, hasActiveScheduleOf, increasedForkTitle, instanceSnapshotSignature, mergeRuntimeFacts, mergeSearchResults, nextServerOrder, nextUpdatedOrder, orderServersForDisplay, orderUngroupedSessions, projectInstanceSnapshot, projectRuntimeFacts, reconcileCompletedFacts, reconciledSessionOrder, relativeTimeBucket, runningRingVisible, runtimeReportSignature, sanitizeSearchQuery, serversProjectionSignature, sessionDisplayTitle, sourceAccentColor, workspaceAccentStyle } from './derive.ts'
export type * from './workspace-echo.ts'
export { forgetPendingWorkspaces, reconcilePendingWorkspaces, recordPendingWorkspace, removePendingWorkspace, renamePendingWorkspace, sweepPendingWorkspaces, withWorkspaceEcho } from './workspace-echo.ts'
export type * from './session-echo.ts'
export { forgetPendingArchives, forgetPendingSessions, reconcilePendingArchives, reconcilePendingSessions, recordPendingArchive, recordPendingSession, refreshPendingArchives, removePendingSession, sweepPendingArchives, sweepPendingSessions, withPendingArchives, withSessionEcho } from './session-echo.ts'
export type * from './session-row-state.ts'
export { sessionRowState, subagentActivityOf } from './session-row-state.ts'
export type * from './session-create-ledger.ts'
export { publishSessionCreationInstrument, sessionCreationLedger } from './session-create-ledger.ts'
export type * from './session-mutations.ts'
export { archiveSessionForSource, createSessionForSource, forkSessionForSource } from './session-mutations.ts'
export type * from './open-intent.ts'
export { EARLY_OPEN_BUDGET_MS, EARLY_OPEN_RETRY_MS, armOpenIntent, clearOpenIntents, getOpenIntent, getOpenIntentsSnapshot, projectableCurrent, releaseOpenIntent, shouldEarlyOpenSession, shouldHoldViewVeil, subscribeOpenIntent } from './open-intent.ts'
export type * from './gateway-runtime.ts'
export { REMOTE_PHASES, REMOTE_RESTART, REMOTE_SOURCES, REMOTE_STATUS_POLL_TIMEOUT_MS, fetchRemoteRuntimeStatus, fetchRemoteRuntimeVersions, pollRemoteRuntimeUntilSettled, remoteRuntimeAction, remoteRuntimeActionGates, remoteRuntimeSetRegistry, resetRemoteRuntimeActivityOwners } from './gateway-runtime.ts'
export type * from './gateway-runtime-poll.ts'
export { pollGatewayReady } from './gateway-runtime-poll.ts'
export type * from './managed-runtime.ts'
export { MANAGED_RUNTIME_TRANSIENT_STATES, fetchManagedRuntimeState, managedRuntimeDown, managedRuntimeUnusable } from './managed-runtime.ts'
export type * from './runtime-refusal.ts'
export { classifyRuntimeRefusal, serverRefusalText } from './runtime-refusal.ts'
export type * from './error-text.ts'
export { describeThrown, errorMessage } from './error-text.ts'
export type * from './boot-gap-shape.ts'
export { bootGapShape } from './boot-gap-shape.ts'
export type * from './view-prefs.ts'
export { clearSourceBookkeeping, flushScheduledActivityWrites, getViewPrefs, scheduleUpdatedOrderWrite, subscribeViewPrefs, updateViewPrefs } from './view-prefs.ts'
export type * from './search-state.ts'
export { clearSearch, collapseSearch, expandSearch, getSearchStates, setSearchFetcher, setSearchQuery, subscribeSearch } from './search-state.ts'
export type * from './pending-click.ts'
export { clearPendingClick, isClickInsidePendingRow, noteSessionRowClick } from './pending-click.ts'
export type * from './hover-intent.ts'
export { HOVER_OPEN_DELAY_MS, createHoverIntent, dismissVisibleRowCard } from './hover-intent.ts'
export type * from './prewarm-intent.ts'
export { createPrewarmIntent, emptyIntentPrewarmBudget, intentPrewarmAllowed, intentPrewarmSpent, prioritizePrewarmSource } from './prewarm-intent.ts'
export type * from './workspace-git-flags.ts'
export { clearWorkspaceGitFlags, getSourceRepoLayouts, getWorkspaceGitFlag, getWorkspaceGitFlagsVersion, hiddenByMainWorkspaceFold, isSourceGitFlagsLoaded, markSourceGitFlagsLoaded, retainSourceWorkspaceFlags, setSourceRepoLayouts, setWorkspaceGitFlag, subscribeWorkspaceGitFlags } from './workspace-git-flags.ts'
export type * from './workspace-drag-order.ts'
export { resolveWorkspaceDrop } from './workspace-drag-order.ts'
export type * from './todo-attention.ts'
export { deriveTodoAttention } from './todo-attention.ts'
export type * from './todo-prefs.ts'
export { getTodoPrefs, subscribeTodoPrefs } from './todo-prefs.ts'
