/**
 * Bundled-pnpm provisioning for the managed host (design 02 §3.1).
 *
 * The packaged app ships the pinned pnpm as an execute-by-node script
 * (`pnpm/bin/pnpm.cjs`: mode 0644, shebang `#!/usr/bin/env node`) and a
 * Finder-launched app has no node on PATH, so that artifact can never be found by
 * a PATH lookup. Upstream's plugin manager spawns a literal `pnpm` from PATH
 * (`execa('pnpm')` over the managed host's own environment), and its only other
 * seam — the `ProfilePnpmInvocation` boot option — is not reachable from the
 * shipped CLI. This module therefore materializes an executable wrapper inside the
 * control plane's private state area and prepends its directory to ONE managed
 * host's PATH.
 *
 * Rules (design 02 §3.1):
 *  - A host PATH that already resolves a usable `pnpm` is left byte-identical, so
 *    the user's toolchain (and project corepack semantics) is never shadowed.
 *  - The wrapper is re-checked on every spawn from the resolved node + pnpm entry
 *    and rewritten only when that pair (or the pinned mode) changed, so an app move
 *    (macOS App Translocation) or a runtime update cannot leave a stale absolute
 *    path behind.
 *  - Provisioning never fails a spawn: a wrapper that cannot be prepared is logged
 *    loud and the host keeps its own PATH (upstream's ENOENT stays honest).
 *
 * The probe mirrors the resolver the child itself uses (execa → which-command):
 * PATH order, PATHEXT on Windows, entries resolved against the CHILD cwd (an empty
 * entry means the cwd, an unset PATH contributes nothing), quoted Windows entries
 * unwrapped, and only a regular executable counts. Deliberate narrowing: a Windows
 * App Execution Alias whose stat reports EACCES is accepted as executable (as
 * which-command does), while MSYS-style extensionless shims are not detected.
 */

import { lstatSync, readFileSync, statSync } from 'node:fs'
import { isAbsolute, join, resolve } from 'node:path'
import {
  atomicWritePrivateFileNoFollow,
  ensurePrivateDirectoryNoFollow,
  isExecutableFile,
} from './private-file.ts'

/** The wrapper directory under the control plane's state root. */
export const PNPM_SHIM_DIR = 'pnpm-shim'

/** The wrapper's mode: owner-executable; pnpm itself must be spawnable by the host user. */
const PNPM_SHIM_MODE = 0o755

/** PATH separator for a platform. */
function pathDelimiter(platform: NodeJS.Platform): string {
  return platform === 'win32' ? ';' : ':'
}

/** Quote one POSIX shell word; an embedded quote must not break the exec line. */
export function posixQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`
}

/**
 * The wrapper text: run the resolved node (plus its own args/env, e.g. Electron's
 * `ELECTRON_RUN_AS_NODE=1`) over the resolved pnpm entry and forward every argument.
 * Generated, never hand-edited; re-checked on every spawn.
 */
export function pnpmShimScript(input: {
  platform: NodeJS.Platform
  nodeFile: string
  nodeArgs?: readonly string[]
  nodeEnv?: Readonly<Record<string, string>>
  pnpmEntry: string
}): string {
  const nodeArgs = input.nodeArgs ?? []
  const nodeEnv = input.nodeEnv ?? {}
  if (input.platform === 'win32') {
    const assignments = Object.entries(nodeEnv)
      .map(([name, value]) => `set "${name}=${escapeBatch(value)}"`)
    const command = [input.nodeFile, ...nodeArgs, input.pnpmEntry]
      .map(value => `"${escapeBatch(value)}"`)
      .join(' ')
    return [
      '@echo off',
      'rem Generated by dsh-chamber for the bundled pnpm (design 02 §3.1) - do not edit; rewritten per spawn.',
      ...assignments,
      `${command} %*`,
      '',
    ].join('\r\n')
  }
  const assignments = Object.entries(nodeEnv).map(([name, value]) => `export ${name}=${posixQuote(value)}`)
  const command = [input.nodeFile, ...nodeArgs, input.pnpmEntry].map(posixQuote).join(' ')
  return [
    '#!/bin/sh',
    '# Generated by dsh-chamber for the bundled pnpm (design 02 §3.1) - do not edit; rewritten per spawn.',
    ...assignments,
    `exec ${command} "$@"`,
    '',
  ].join('\n')
}

/** Percent signs are the only batch metacharacter that survives inside quotes. */
function escapeBatch(value: string): string {
  return value.replaceAll('%', '%%')
}

/**
 * The env key spelling PATH actually uses: on POSIX the child reads the
 * case-sensitive `PATH` only (cross-spawn's path-key does the same), while Windows
 * may hand us `Path`.
 */
function pathKeyOf(env: NodeJS.ProcessEnv, platform: NodeJS.Platform): string | null {
  if (platform !== 'win32') return Object.hasOwn(env, 'PATH') ? 'PATH' : null
  for (const key of Object.keys(env)) {
    if (key.toUpperCase() === 'PATH') return key
  }
  return null
}

/** Case-sensitive env lookup on POSIX, case-insensitive on Windows (`Path`/`PATHEXT`). */
function envValue(env: NodeJS.ProcessEnv, name: string, platform: NodeJS.Platform): string | undefined {
  if (platform !== 'win32') return env[name]
  for (const key of Object.keys(env)) {
    if (key.toUpperCase() === name.toUpperCase()) return env[key]
  }
  return undefined
}

/** A regular file: a same-named directory must never satisfy a command lookup. */
function isRegularFile(target: string): boolean {
  try {
    return statSync(target).isFile()
  } catch {
    return false
  }
}

/** Windows PATH entries are sometimes written quoted; the lookups strip the quotes. */
function stripSurroundingQuotes(entry: string): string {
  return entry.length > 1 && entry.startsWith('"') && entry.endsWith('"') ? entry.slice(1, -1) : entry
}

/** Windows may expose `pnpm` as an App Execution Alias the resolver cannot stat
 *  (EACCES) while the child still executes it — which-command counts that as a hit. */
function isWindowsAliasCandidate(candidate: string): boolean {
  try {
    statSync(candidate)
    return false
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === 'EACCES'
  }
}

/** Candidate names a PATH lookup tries on Windows (PATHEXT order, pnpm stem). */
function windowsPnpmNames(pathExt: string | undefined): string[] {
  const extensions = (pathExt ?? '.COM;.EXE;.BAT;.CMD')
    .split(';')
    .map(extension => extension.trim())
    .filter(extension => extension !== '')
  return extensions.map(extension => `pnpm${extension}`)
}

/**
 * First `pnpm` the managed child's own command lookup resolves, or null: PATH
 * directories in order, PATHEXT extensions on Windows, each entry resolved against
 * `cwd` (an empty entry is the cwd), an unset PATH contributing nothing.
 */
export function pathProvidesPnpm(
  pathValue: string | undefined,
  platform: NodeJS.Platform,
  isExecutable: (file: string) => boolean,
  options: { pathExt?: string; cwd?: string } = {},
): string | null {
  if (pathValue === undefined) return null
  const names = platform === 'win32' ? windowsPnpmNames(options.pathExt) : ['pnpm']
  const cwd = options.cwd ?? process.cwd()
  for (const raw of pathValue.split(pathDelimiter(platform))) {
    const dir = resolve(cwd, stripSurroundingQuotes(raw))
    for (const name of names) {
      const candidate = join(dir, name)
      if (isExecutable(candidate) || (platform === 'win32' && isWindowsAliasCandidate(candidate))) {
        return candidate
      }
    }
  }
  return null
}

/** Read the existing wrapper, or null when absent/unsafe/not a regular file. */
function readExistingShim(file: string, platform: NodeJS.Platform): { content: string; modeOk: boolean } | null {
  try {
    const stat = lstatSync(file)
    if (!stat.isFile()) return null
    const modeOk = platform === 'win32' || (stat.mode & 0o777) === PNPM_SHIM_MODE
    return { content: readFileSync(file, 'utf8'), modeOk }
  } catch {
    return null
  }
}

/**
 * Materialize the wrapper under `<root>/pnpm-shim` and return its directory.
 * Content and mode are both pinned: a wrapper left by an older run with the same
 * content but a wrong mode is repaired, not accepted. The directory follows the
 * shared private-state discipline (0700, no-follow, foreign owners refused).
 */
export function ensurePnpmShim(input: {
  root: string
  pnpmEntry: string
  nodeFile: string
  nodeArgs?: readonly string[]
  nodeEnv?: Readonly<Record<string, string>>
  platform?: NodeJS.Platform
}): string {
  const platform = input.platform ?? process.platform
  const dir = join(input.root, PNPM_SHIM_DIR)
  ensurePrivateDirectoryNoFollow(dir, 0o700)
  const file = join(dir, platform === 'win32' ? 'pnpm.cmd' : 'pnpm')
  const script = pnpmShimScript({
    platform,
    nodeFile: input.nodeFile,
    nodeArgs: input.nodeArgs,
    nodeEnv: input.nodeEnv,
    pnpmEntry: input.pnpmEntry,
  })
  const existing = readExistingShim(file, platform)
  if (existing === null || existing.content !== script || !existing.modeOk) {
    atomicWritePrivateFileNoFollow(file, script, { mode: PNPM_SHIM_MODE })
  }
  return dir
}

interface PnpmShimOptions {
  /** The control plane's state root; the wrapper lives at `<stateDir>/pnpm-shim`. */
  stateDir: string
  /** The resolved bundled pnpm entry; null/undefined means this caller did not opt in. */
  pnpmEntry: string | null | undefined
  /** The node that runs the managed host (resolveNodeExecutable). */
  nodeFile: string
  nodeArgs?: readonly string[]
  nodeEnv?: Readonly<Record<string, string>>
  /** The cwd the managed host will run in; empty/relative PATH entries resolve there. */
  cwd?: string
  platform?: NodeJS.Platform
  log?: (line: string) => void
}

/**
 * Return `env` for one managed host with the bundled pnpm reachable: unchanged when
 * the host's own PATH already resolves a pnpm (or when provisioning is impossible),
 * otherwise with the wrapper directory prepended to the host PATH.
 */
export function withPnpmShim(env: NodeJS.ProcessEnv, options: PnpmShimOptions): NodeJS.ProcessEnv {
  const platform = options.platform ?? process.platform
  const { pnpmEntry, nodeFile } = options
  // Diagnostics only: a throwing sink must never fail a spawn.
  const emit = (line: string): void => {
    try {
      options.log?.(line)
    } catch {
      /* see above */
    }
  }
  if (pnpmEntry === null || pnpmEntry === undefined) return env
  if (
    pnpmEntry === ''
    || !isAbsolute(nodeFile)
    || !isAbsolute(pnpmEntry)
    || !isRegularFile(nodeFile)
    || !isRegularFile(pnpmEntry)
  ) {
    emit(`pnpm: bundled launcher unavailable (node ${nodeFile}, entry ${pnpmEntry}); the managed host keeps its PATH as-is`)
    return env
  }
  const pathKey = pathKeyOf(env, platform)
  const provided = pathProvidesPnpm(
    pathKey === null ? undefined : env[pathKey],
    platform,
    isExecutableFile,
    {
      pathExt: platform === 'win32' ? envValue(env, 'PATHEXT', platform) : undefined,
      cwd: options.cwd ?? process.cwd(),
    },
  )
  if (provided !== null) {
    emit(`pnpm: managed host PATH already provides ${provided}; the bundled launcher is not injected`)
    return env
  }
  let dir: string
  try {
    dir = ensurePnpmShim({
      root: options.stateDir,
      pnpmEntry,
      nodeFile,
      nodeArgs: options.nodeArgs,
      nodeEnv: options.nodeEnv,
      platform,
    })
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    emit(`pnpm: managed host PATH has no pnpm and the bundled launcher could not be prepared (${reason}); PATH left unchanged`)
    return env
  }
  const key = pathKey ?? 'PATH'
  const current = env[key]
  emit(`pnpm: prepended the bundled launcher to the managed host PATH (${dir})`)
  return {
    ...env,
    [key]: current === undefined || current === '' ? dir : `${dir}${pathDelimiter(platform)}${current}`,
  }
}
