/**
 * Build-level smoke test (design 17 §9.4 regression): the gateway esbuild
 * bundle must carry the createRequire banner and import cleanly. 2026-12: the
 * ws-based session-index / approval-stream transports were removed with the
 * orchestration strip, so the bundle no longer contains ws — the banner stays
 * as belt-and-braces for any remaining bundled CJS dep with static requires.
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const packageDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const distIndex = join(packageDir, 'dist', 'index.js')

test('gateway dist bundle carries the createRequire banner and imports cleanly', async () => {
  // dist/ is gitignored: build on demand so the smoke test works from a
  // clean checkout (the build is a fast esbuild step).
  if (!existsSync(distIndex)) {
    execFileSync(process.execPath, ['scripts/build.mjs'], { cwd: packageDir, stdio: 'ignore' })
  }
  const source = await readFile(distIndex, 'utf8')
  // The banner (scripts/build.mjs) installs a module-scoped require shim so
  // any bundled CJS dep's static requires resolve node builtins normally.
  assert.match(source, /import \{ createRequire \} from 'node:module';/, 'the createRequire banner import is present')
  assert.match(source, /const require = createRequire\(import\.meta\.url\);/, 'the banner require shim is installed')
  // 2026-12: the ws transports are gone with the orchestration strip — the
  // bundle must NOT carry ws's static require("events") any more.
  assert.equal(source.includes('ws/lib/websocket.js'), false, 'the ws websocket transport is no longer bundled')
  // And the bundle must import cleanly (no "Dynamic require") and expose the
  // public API surface the control plane consumes.
  const module = await import(pathToFileURL(distIndex).href)
  assert.equal(typeof module.createGateway, 'function')
  assert.equal(typeof module.createChamberSurface, 'function')
  assert.equal(typeof module.createGatewayStore, 'function')
})

test('dist bundles the pinned pnpm the installer local path relies on (design 18 §9.2 D1)', async () => {
  // dist/ is gitignored: build on demand so the smoke test works from a
  // clean checkout (same as the banner test above).
  const pnpmBin = join(packageDir, 'dist', 'pnpm', 'bin', 'pnpm.cjs')
  if (!existsSync(pnpmBin)) {
    execFileSync(process.execPath, ['scripts/build.mjs'], { cwd: packageDir, stdio: 'ignore' })
  }
  assert.ok(existsSync(pnpmBin), 'scripts/build.mjs must copy the pinned pnpm into dist/pnpm')
  // Dynamic assertion: the bundled pnpm version must equal the gateway
  // manifest's dependencies.pnpm (build.mjs enforces the same guard at build
  // time; re-asserting here keeps a stale dist from slipping through the
  // smoke). The alternative (hardcoding 11.21.0) would drift from
  // package.json, which is the single source of truth.
  const manifest = JSON.parse(await readFile(join(packageDir, 'package.json'), 'utf8')) as {
    dependencies: { pnpm: string }
  }
  const bundled = JSON.parse(await readFile(join(packageDir, 'dist', 'pnpm', 'package.json'), 'utf8')) as {
    name: string
    version: string
  }
  assert.equal(bundled.name, 'pnpm')
  assert.equal(bundled.version, manifest.dependencies.pnpm,
    'bundled pnpm version must match the gateway dependencies.pnpm pin')
  // And the bundled pnpm must actually run from the unpacked tree shape —
  // that is exactly how the installer local path spawns it (plain `node
  // pnpm.cjs`, no npm-installed dependency tree).
  const run = spawnSync(process.execPath, [pnpmBin, '--version'], { cwd: packageDir, encoding: 'utf8' })
  assert.equal(run.status, 0, `node dist/pnpm/bin/pnpm.cjs --version failed: ${run.stderr}`)
  assert.ok(run.stdout.includes(manifest.dependencies.pnpm),
    `--version output ${JSON.stringify(run.stdout)} must report the pinned version`)
})

// ---- mobile seed artifact contract (design 17 §18.3, P0 regression) ----

test('host-packages carries the mobile seed set, aligned with exports and seedFiles', () => {
  // host-packages/ is generated by scripts/build.mjs; build on demand so the
  // smoke test works from a clean checkout.
  const hostDir = join(packageDir, 'host-packages', 'dsh-chamber-client-ui-mobile')
  if (!existsSync(join(hostDir, 'lib', 'index.js'))) {
    execFileSync(process.execPath, ['scripts/build.mjs'], { cwd: packageDir, stdio: 'ignore' })
  }
  // Every file the package manifest points at must be present (the cordis
  // loader imports the overlay row by package name → `main`/exports["."],
  // and the ClientModuleRegistry serves exports["./client"] — omitting any
  // of them fails the managed dsh boot).
  for (const file of ['package.json', 'dist/index.js', 'lib/index.js', 'lib/client.js', 'lib/client.js.map']) {
    assert.equal(existsSync(join(hostDir, file)), true, `missing seeded file ${file}`)
  }
  const manifest = JSON.parse(readFileSync(join(hostDir, 'package.json'), 'utf8'))
  const dot = manifest.exports?.['.'] ?? { default: manifest.main }
  assert.equal(dot.default, './lib/index.js', 'exports["."] must resolve to a seeded file')
  assert.equal(manifest.exports?.['./client'], './lib/client.js', 'exports["./client"] must resolve to a seeded file')
})
