/**
 * The gateway's pnpm PATH shim + entry binding.
 *
 * The managed `dsh plugin` CLI spawns a literal `pnpm` from PATH and answers 127
 * when the server has none; the gateway ships the pinned pnpm as a bare
 * `dist/pnpm/bin/pnpm.cjs`, invisible to a PATH lookup.
 *
 * The shim is generated, not shipped: two wrappers exec the bundled pnpm through
 * node inside the gateway-owned 0700 area, idempotently (content-compared).
 * Entry RESOLUTION stays the shared core's.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire as nodeCreateRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolvePnpmEntry as resolveSharedPnpmEntry } from '@dsh-chamber/dsh-runtime'

const gatewayRequire = nodeCreateRequire(import.meta.url)

/** Directory name (under the gateway's third-party root) holding the shim. */
export const PNPM_SHIM_DIR = 'pnpm-shim'

/** Platform PATH separator (`:` POSIX, `;` Windows). */
export function pathDelimiter(): string {
  return process.platform === 'win32' ? ';' : ':'
}

/**
 * Package-resolution fallback entries for the dev / npm-installed shape: pnpm is
 * a real dependency there and its `exports` hides `./bin/pnpm.cjs`; a resolution
 * failure yields NO entry (never a throw), so the bundled copy can still win.
 */
function packagePnpmEntries(): readonly string[] {
  try {
    return [join(dirname(gatewayRequire.resolve('pnpm')), 'bin', 'pnpm.cjs')]
  } catch {
    return []
  }
}

/**
 * Absolute path of the pnpm entry script the gateway runs: the bundled
 * `dist/pnpm` copy first (`fileURLToPath`, since `path.dirname` would mangle a
 * `file://` URL), then the resolved `pnpm` package bin. When every candidate is
 * absent the shared resolver returns its first, so existence stays the caller's
 * business (loud failure, never a silently different pnpm).
 */
export function resolvePnpmEntry(): string {
  return resolveSharedPnpmEntry({
    platform: process.platform,
    execPath: process.execPath,
    env: process.env,
    bundledDir: dirname(fileURLToPath(import.meta.url)),
    explicitEntries: packagePnpmEntries(),
  })
}

/** POSIX wrapper: exec the bundled pnpm through node; quoting survives spaces
 * and `"$@"` forwards argv verbatim. */
function posixShim(pnpmEntry: string, execPath: string): string {
  return `#!/bin/sh\n# Generated by dsh-chamber gateway (pnpm PATH shim) — do not edit.\nexec "${execPath}" "${pnpmEntry}" "$@"\n`
}

/** Windows wrapper: upstream spawns `pnpm` with `shell: true`, which resolves
 * `pnpm.cmd`; `%*` forwards argv. */
function windowsShim(pnpmEntry: string, execPath: string): string {
  return `@echo off\r\nrem Generated by dsh-chamber gateway (pnpm PATH shim) - do not edit.\r\n"${execPath}" "${pnpmEntry}" %*\r\n`
}

/** Write `file` only when its content differs (idempotent for concurrent
 * mutations writing identical bytes), then pin the mode. */
function writeIdempotent(file: string, content: string, mode: number): void {
  try {
    if (readFileSync(file, 'utf8') === content) return
  } catch {
    // absent or unreadable — fall through to the write
  }
  writeFileSync(file, content, { mode })
  chmodSync(file, mode)
}

/**
 * Ensure a directory holding an executable `pnpm` (and `pnpm.cmd` on Windows)
 * that forwards to the bundled pnpm, and return it for PATH prepend. Returns null
 * when it cannot be created: the caller leaves PATH untouched and the upstream
 * 127 stays honest.
 */
export function ensurePnpmOnPath(root: string): string | null {
  try {
    const entry = resolvePnpmEntry()
    if (!existsSync(entry)) return null
    const dir = join(root, PNPM_SHIM_DIR)
    mkdirSync(dir, { recursive: true, mode: 0o700 })
    const execPath = process.execPath
    if (process.platform === 'win32') {
      writeIdempotent(join(dir, 'pnpm.cmd'), windowsShim(entry, execPath), 0o755)
    } else {
      writeIdempotent(join(dir, 'pnpm'), posixShim(entry, execPath), 0o755)
    }
    return dir
  } catch {
    return null
  }
}

/** Prepend a resolved pnpm directory to an env's PATH (`dir` null = untouched). */
export function withPnpmOnPath<T extends Record<string, string | undefined>>(env: T, dir: string | null): T {
  if (dir === null) return env
  return { ...env, PATH: `${dir}${pathDelimiter()}${env.PATH ?? ''}` }
}
