/**
 * The gateway's own pnpm: resolution + PATH shim (design 18 §9.2 D1, design 21
 * §6.3).
 *
 * Why this exists: the managed `dsh plugin` CLI is a thin pnpm forwarder —
 * upstream spawns a literal `pnpm` from PATH and answers 127
 * ("pnpm not found on PATH") when the server has none
 * (`apps/cli/src/plugin.ts`, verified against the pinned dsh-v0.1.5-rc.1). The
 * gateway ships the pinned pnpm as a bare `dist/pnpm/bin/pnpm.cjs` script (used
 * by the runtime installer through {@link resolvePnpmEntry}), which is not an
 * executable named `pnpm` and therefore invisible to a PATH lookup. A gateway
 * deployed on a host provisioned with npm alone could not seed or mutate the
 * managed profile at all (2026-09 audit, P1).
 *
 * The shim is generated, not shipped: two tiny wrappers that exec the bundled
 * pnpm through the current node binary. The directory is derived from the
 * state dir so it stays inside the gateway-owned 0700 area, and generation is
 * idempotent (content-compared) so concurrent mutations cannot race a rewrite.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire as nodeCreateRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const gatewayRequire = nodeCreateRequire(import.meta.url)

/** Directory name (under the gateway's third-party root) holding the shim. */
export const PNPM_SHIM_DIR = 'pnpm-shim'

/** Platform PATH separator (`:` POSIX, `;` Windows). */
export function pathDelimiter(): string {
  return process.platform === 'win32' ? ';' : ':'
}

/**
 * Absolute path of the pnpm entry script the gateway runs.
 *
 * Bundled shape first (design 18 §9.2 D1): the installer's local path unpacks
 * the gateway tarball and NEVER installs gateway dependencies, so resolving the
 * `pnpm` package cannot hit a real `node_modules` tree there. `scripts/build.mjs`
 * copies the pinned pnpm into `dist/pnpm`; prefer it whenever the build carried
 * it. NOTE: `dist/pnpm` sits next to the bundled module, so the path is derived
 * with `fileURLToPath` — `path.dirname` over a `file://` URL would mangle it.
 *
 * Dev / npm-installed shape: pnpm is a real runtime dependency of the gateway.
 * Its `package.json` `exports` hides `./bin/pnpm.cjs`
 * (ERR_PACKAGE_PATH_NOT_EXPORTED), so the package entry is resolved and the bin
 * path joined by hand.
 *
 * @returns the absolute pnpm entry path (existence is the caller's business in
 *   the dev shape; the bundled shape is checked here).
 */
export function resolvePnpmEntry(): string {
  const bundled = join(dirname(fileURLToPath(import.meta.url)), 'pnpm', 'bin', 'pnpm.cjs')
  if (existsSync(bundled)) return bundled
  return join(dirname(gatewayRequire.resolve('pnpm')), 'bin', 'pnpm.cjs')
}

/** POSIX wrapper: exec the bundled pnpm through the current node binary.
 * Quoted paths survive spaces; `"$@"` forwards argv verbatim. */
function posixShim(pnpmEntry: string, execPath: string): string {
  return `#!/bin/sh\n# Generated by dsh-chamber gateway (pnpm PATH shim) — do not edit.\nexec "${execPath}" "${pnpmEntry}" "$@"\n`
}

/** Windows wrapper: upstream spawns `pnpm` with `shell: true`, which resolves
 * `pnpm.cmd` from PATH. `%*` forwards argv; quoting keeps spaced paths intact. */
function windowsShim(pnpmEntry: string, execPath: string): string {
  return `@echo off\r\nrem Generated by dsh-chamber gateway (pnpm PATH shim) - do not edit.\r\n"${execPath}" "${pnpmEntry}" %*\r\n`
}

/** Write `file` only when its content differs (idempotent, race-safe enough for
 * two concurrent mutations writing identical bytes), then pin the mode. */
function writeIdempotent(file: string, content: string, mode: number): void {
  try {
    if (readFileSync(file, 'utf8') === content) return
  } catch {
    // absent or unreadable — fall through to the write
  }
  writeFileSync(file, content, { mode })
  chmodSync(file, mode)
}

/**
 * Ensure a directory holding an executable `pnpm` (and `pnpm.cmd` on Windows)
 * that forwards to the gateway's bundled pnpm, and return it for PATH prepend.
 *
 * @param root - gateway-owned directory the shim lives under (0700 area).
 * @returns the shim directory, or null when it cannot be created (the caller
 *   then leaves PATH untouched and the upstream 127 stays honest instead of
 *   being masked by a half-written shim).
 */
export function ensurePnpmOnPath(root: string): string | null {
  try {
    const entry = resolvePnpmEntry()
    if (!existsSync(entry)) return null
    const dir = join(root, PNPM_SHIM_DIR)
    mkdirSync(dir, { recursive: true, mode: 0o700 })
    const execPath = process.execPath
    if (process.platform === 'win32') {
      writeIdempotent(join(dir, 'pnpm.cmd'), windowsShim(entry, execPath), 0o755)
    } else {
      writeIdempotent(join(dir, 'pnpm'), posixShim(entry, execPath), 0o755)
    }
    return dir
  } catch {
    return null
  }
}

/**
 * Prepend a resolved pnpm directory to an env's PATH (the shared shape used by
 * the plugin executor and the local `dsh plugin` path).
 *
 * @param env - the child env (mutated copy returned).
 * @param dir - the pnpm directory, or null to leave PATH untouched.
 * @returns the env with PATH prefixed.
 */
export function withPnpmOnPath<T extends Record<string, string | undefined>>(env: T, dir: string | null): T {
  if (dir === null) return env
  return { ...env, PATH: `${dir}${pathDelimiter()}${env.PATH ?? ''}` }
}
