/**
 * The gateway's pnpm PATH shim + entry binding (design 18 §9.2 D1, design 21
 * §6.3).
 *
 * Why the shim exists: the managed `dsh plugin` CLI is a thin pnpm forwarder —
 * upstream spawns a literal `pnpm` from PATH and answers 127
 * ("pnpm not found on PATH") when the server has none
 * (`apps/cli/src/plugin.ts`). The
 * gateway ships the pinned pnpm as a bare `dist/pnpm/bin/pnpm.cjs` script,
 * which is not an executable named `pnpm` and therefore invisible to a PATH
 * lookup. A gateway deployed on a host provisioned with npm alone could not
 * seed or mutate the managed profile at all.
 *
 * The shim is generated, not shipped: two tiny wrappers that exec the bundled
 * pnpm through the current node binary. The directory is derived from the
 * state dir so it stays inside the gateway-owned 0700 area, and generation is
 * idempotent (content-compared) so concurrent mutations cannot race a rewrite.
 *
 * Entry RESOLUTION is not gateway-owned: the candidate order lives in the
 * shared core (`@dsh-chamber/dsh-runtime` pnpm-entry.ts) — bundled copy first,
 * then the package-resolution fallback this file contributes through
 * `explicitEntries`. Only the shim/PATH mechanics below are gateway-specific.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire as nodeCreateRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolvePnpmEntry as resolveSharedPnpmEntry } from '@dsh-chamber/dsh-runtime'

const gatewayRequire = nodeCreateRequire(import.meta.url)

/** Directory name (under the gateway's third-party root) holding the shim. */
export const PNPM_SHIM_DIR = 'pnpm-shim'

/** Platform PATH separator (`:` POSIX, `;` Windows). */
export function pathDelimiter(): string {
  return process.platform === 'win32' ? ';' : ':'
}

/**
 * The package-resolution fallback entries for the dev / npm-installed shape:
 * pnpm is a real runtime dependency there, and its `package.json` `exports`
 * hides `./bin/pnpm.cjs` (ERR_PACKAGE_PATH_NOT_EXPORTED), so the package entry
 * is resolved and the bin path joined by hand.
 *
 * A resolution failure yields NO explicit entry instead of throwing: a bundled
 * deployment (the installer's local path unpacks the gateway tarball and NEVER
 * installs gateway dependencies) has no `pnpm` package to resolve, and the
 * shared resolver must still be able to prefer the bundled copy there.
 */
function packagePnpmEntries(): readonly string[] {
  try {
    return [join(dirname(gatewayRequire.resolve('pnpm')), 'bin', 'pnpm.cjs')]
  } catch {
    return []
  }
}

/**
 * Absolute path of the pnpm entry script the gateway runs — the shared core's
 * first existing candidate.
 *
 * Bundled shape first (design 18 §9.2 D1): `scripts/build.mjs` copies the
 * pinned pnpm into `dist/pnpm`, and the shared resolver is handed
 * `bundledDir` = this module's directory, so that copy wins whenever the build
 * carried it. NOTE `dist/pnpm` sits next to the bundled module, so the path is
 * derived with `fileURLToPath` — `path.dirname` over a `file://` URL would
 * mangle it. The dev / npm-installed shape follows with the resolved `pnpm`
 * package bin.
 *
 * @returns the absolute pnpm entry path; when every candidate is absent the
 *   shared resolver returns its first candidate, so existence stays the
 *   caller's business (loud failure, never a silently different pnpm).
 */
export function resolvePnpmEntry(): string {
  return resolveSharedPnpmEntry({
    platform: process.platform,
    execPath: process.execPath,
    env: process.env,
    bundledDir: dirname(fileURLToPath(import.meta.url)),
    explicitEntries: packagePnpmEntries(),
  })
}

/** POSIX wrapper: exec the bundled pnpm through the current node binary.
 * Quoted paths survive spaces; `"$@"` forwards argv verbatim. */
function posixShim(pnpmEntry: string, execPath: string): string {
  return `#!/bin/sh\n# Generated by dsh-chamber gateway (pnpm PATH shim) — do not edit.\nexec "${execPath}" "${pnpmEntry}" "$@"\n`
}

/** Windows wrapper: upstream spawns `pnpm` with `shell: true`, which resolves
 * `pnpm.cmd` from PATH. `%*` forwards argv; quoting keeps spaced paths intact. */
function windowsShim(pnpmEntry: string, execPath: string): string {
  return `@echo off\r\nrem Generated by dsh-chamber gateway (pnpm PATH shim) - do not edit.\r\n"${execPath}" "${pnpmEntry}" %*\r\n`
}

/** Write `file` only when its content differs (idempotent, race-safe enough for
 * two concurrent mutations writing identical bytes), then pin the mode. */
function writeIdempotent(file: string, content: string, mode: number): void {
  try {
    if (readFileSync(file, 'utf8') === content) return
  } catch {
    // absent or unreadable — fall through to the write
  }
  writeFileSync(file, content, { mode })
  chmodSync(file, mode)
}

/**
 * Ensure a directory holding an executable `pnpm` (and `pnpm.cmd` on Windows)
 * that forwards to the gateway's bundled pnpm, and return it for PATH prepend.
 *
 * @param root - gateway-owned directory the shim lives under (0700 area).
 * @returns the shim directory, or null when it cannot be created (the caller
 *   then leaves PATH untouched and the upstream 127 stays honest instead of
 *   being masked by a half-written shim).
 */
export function ensurePnpmOnPath(root: string): string | null {
  try {
    const entry = resolvePnpmEntry()
    if (!existsSync(entry)) return null
    const dir = join(root, PNPM_SHIM_DIR)
    mkdirSync(dir, { recursive: true, mode: 0o700 })
    const execPath = process.execPath
    if (process.platform === 'win32') {
      writeIdempotent(join(dir, 'pnpm.cmd'), windowsShim(entry, execPath), 0o755)
    } else {
      writeIdempotent(join(dir, 'pnpm'), posixShim(entry, execPath), 0o755)
    }
    return dir
  } catch {
    return null
  }
}

/**
 * Prepend a resolved pnpm directory to an env's PATH (the shared shape used by
 * the plugin executor and the local `dsh plugin` path).
 *
 * @param env - the child env (mutated copy returned).
 * @param dir - the pnpm directory, or null to leave PATH untouched.
 * @returns the env with PATH prefixed.
 */
export function withPnpmOnPath<T extends Record<string, string | undefined>>(env: T, dir: string | null): T {
  if (dir === null) return env
  return { ...env, PATH: `${dir}${pathDelimiter()}${env.PATH ?? ''}` }
}
