import { existsSync, realpathSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * dsh-chamber renderer build (design 05 §2/§3.6, v4).
 *
 * The frontend is the dsh official web frontend, source-reused and self-built:
 * the shell entry (`index.html` → `src/main.tsx`) hosts the chamber chrome
 * (auth gate / instance sidebar / management view) and the dsh boot kernel
 * (AppWebEntry per instance); the `chamber` entry is the single boot-graph
 * plugin bundle (one entry registering every ui-* client plugin via
 * ctx.plugin()). This mirrors apps/web's vite configuration: workspace
 * packages resolve to SOURCE so CSS rides the vite pipeline, the vendored
 * cordis Loader gets its node-only import stubbed, and the heavy render
 * families split into a stable vendor chunk.
 *
 * There is no standalone serve: bare Vite cannot inject `window.__DSH_BOOT__`
 * (that is the control plane's job — it serves dist/ and injects the manifest
 * it reads from dist/manifest.json), so `vite serve` refuses to start.
 */

const src = (rel) => fileURLToPath(new URL(rel, import.meta.url))
const STANDALONE_ERROR = 'packages/renderer is not a standalone application: bare Vite cannot inject window.__DSH_BOOT__. '
  + 'The control plane serves the built dist/ and injects the boot manifest it reads from dist/manifest.json '
  + '(generated by scripts/gen-boot-manifest.mjs).'

/** Fail before a Vite dev or preview server can expose the boot-manifest-free shell. */
function rejectStandaloneServe() {
  return {
    name: 'dsh-chamber-reject-standalone-serve',
    config(_config, env) {
      if (env.command === 'serve') throw new Error(STANDALONE_ERROR)
    },
  }
}

/**
 * @deepseek-ai/* workspace resolution to SOURCE (mirrors apps/web's alias
 * list, extended to every package the chamber bundle imports). The vendor
 * tree (`vendor/harness-packages/@deepseek-ai`) is a read-only directory of
 * symlinks into the external dsh checkout; the chamber-copied packages
 * (connection, web, api-gateway — the only dsh source we may modify) resolve
 * to our copies. Subpaths map onto the source tree by convention
 * (`<pkg>/client` → `src/client/index.ts`, …). Every other @deepseek-ai/*
 * package — including the dsh-v0.1.2-alpha.1 provider group
 * (dsh-client-store, api-session-controller, api-workspace-controller,
 * ui-session, ui-chat, ui-approval) — resolves through the generic vendor
 * fallback below.
 */
/**
 * Bare (non-workspace) npm specifiers imported from vendor source: node
 * resolution walks up from the vendor directory (the external dsh checkout,
 * which carries no node_modules), so every such import is resolved from the
 * renderer's own install tree instead (declared in packages/renderer
 * devDependencies — the bundler-consumer pattern apps/web uses). Workspace
 * (@deepseek-ai) and relative specifiers are left to the other plugins.
 */
const requireFromRenderer = createRequire(import.meta.url)

function npmFallback() {
  return {
    name: 'dsh-chamber-npm-fallback',
    enforce: 'pre',
    resolveId(specifier) {
      if (typeof specifier !== 'string') return undefined
      if (specifier.startsWith('.') || specifier.startsWith('/') || specifier.startsWith('node:')
        || specifier.startsWith('@deepseek-ai/')) return undefined
      try {
        return requireFromRenderer.resolve(specifier)
      } catch {
        return undefined
      }
    },
  }
}

function deepseekSource() {
  return {
    name: 'dsh-chamber-deepseek-source',
    enforce: 'pre',
    resolveId(specifier) {
      if (typeof specifier !== 'string' || !specifier.startsWith('@deepseek-ai/')) return undefined
      const rest = specifier.slice('@deepseek-ai/'.length)
      const slash = rest.indexOf('/')
      const name = slash === -1 ? rest : rest.slice(0, slash)
      const sub = slash === -1 ? '' : rest.slice(slash + 1)
      const pick = (...cands) => cands.find((c) => c !== undefined && existsSync(c))
      const real = (p) => realpathSync(p)
      if (name === 'dsh-client-connection' || name === 'dsh-client-web' || name === 'dsh-api-gateway') {
        // The chamber-copied packages (connection, web, and the dsh-v0.1.2-alpha.1
        // api-gateway fork with the per-entry base-path patch) resolve to OUR
        // copies, shadowing the vendor package of the same name. Same source
        // layout for all three: `index.ts` at the package root, `client/` for
        // the /client subpath.
        const base = new URL(`../${name}/src/`, import.meta.url)
        return pick(
          sub === '' ? fileURLToPath(new URL('index.ts', base)) : undefined,
          sub === 'client' ? fileURLToPath(new URL('client/index.ts', base)) : undefined,
        )
      }
      // The `/remote` subpath of typert-contributing packages has no upstream
      // source (src/remote/index.ts does not exist): it resolves to the
      // generator's artifact instead (gen-typert-remotes.mjs writes it from
      // the host face model, mirroring the upstream tsdown output).
      if (sub === 'remote') {
        const artifact = fileURLToPath(new URL(`./src/generated/typert/${name}/typert.remote-client.js`, import.meta.url))
        const hit = pick(artifact)
        if (hit !== undefined) return real(hit)
        return undefined
      }
      const pkgUrl = new URL(`${name}/`, new URL('../../vendor/harness-packages/@deepseek-ai/', import.meta.url))
      if (!existsSync(pkgUrl)) return undefined
      const srcdir = fileURLToPath(new URL('src/', pkgUrl))
      const pickReal = (...cands) => {
        const hit = pick(...cands)
        return hit === undefined ? undefined : real(hit)
      }
      if (sub === '') return pickReal(`${srcdir}index.ts`)
      // Vendor `./src/*` deep subpaths (the canonical export-map form the
      // chamber ui-layout fork imports, e.g.
      // `@deepseek-ai/dsh-client-ui-layout/src/client/AppFrame.tsx`): the
      // specifier already names the src/ directory, so strip the redundant
      // prefix before joining the source tree.
      if (sub.startsWith('src/')) return pickReal(`${srcdir}${sub.slice(4)}`)
      return pickReal(
        `${srcdir}${sub}/index.ts`,
        `${srcdir}${sub}.ts`,
        `${srcdir}${sub}/index.tsx`,
        `${srcdir}${sub}.tsx`,
        // Non-TS deep subpaths (CSS via `./src/*`-style exports and literal
        // source files): resolved straight into the source tree. The `./styles`
        // export of e.g. dsh-client-ui-theme points at the BUILT lib/ tree,
        // which the source-only vendor cannot provide.
        `${srcdir}${sub}`,
      )
    },
  }
}

/**
 * Vendor-chunk membership, by exact npm package name — copied from apps/web
 * (math/highlight/markdown families; only packages workspace code imports
 * DIRECTLY need listing — rollup's chunk coloring pulls the private
 * transitive deps in automatically). Every member must be React-free.
 */
const VENDOR_PACKAGES = new Set([
  'katex',
  'shiki',
  'mdast-util-from-markdown',
  'mdast-util-gfm',
  'mdast-util-math',
  'micromark-core-commonmark',
  'micromark-extension-gfm',
  'micromark-extension-math',
  'micromark-factory-space',
  'micromark-util-character',
  'micromark-util-classify-character',
  'micromark-util-sanitize-uri',
  'micromark-util-symbol',
  'micromark-util-types',
])

/** Boot grammars statically imported by ui-primitives' highlight.ts (vendor chunk; lazy ones stay on-demand). */
const BOOT_GRAMMAR_FILES = ['dist/typescript.mjs', 'dist/shellscript.mjs', 'dist/json.mjs']

/** Font asset extensions routed to assets/fonts/ (KaTeX faces). */
const FONT_EXTENSIONS = ['.woff2', '.woff', '.ttf']

function npmPackageOf(id) {
  const parts = id.split('/node_modules/')
  if (parts.length === 1) return undefined
  const [first, second] = parts[parts.length - 1].split('/')
  if (first.startsWith('.')) return undefined
  if (first.startsWith('@')) return second === undefined ? undefined : `${first}/${second}`
  return first
}

export default defineConfig({
  plugins: [rejectStandaloneServe(), deepseekSource(), npmFallback(), react()],
  base: './',
  build: {
    sourcemap: true,
    manifest: true,
    rollupOptions: {
      input: {
        main: src('./index.html'),
        chamber: src('./src/chamber-entry.ts'),
      },
      output: {
        chunkFileNames(chunk) {
          if (chunk.name === 'index' || chunk.name === 'vendor') return 'assets/[name]-[hash].js'
          const isLangChunk = chunk.moduleIds.some(id => id.includes('/node_modules/@shikijs/langs/'))
          return isLangChunk ? 'assets/langs/[name]-[hash].js' : 'assets/[name]-[hash].js'
        },
        assetFileNames(asset) {
          const fileName = asset.names[0] ?? ''
          const isFont = FONT_EXTENSIONS.some(ext => fileName.endsWith(ext))
          return isFont ? 'assets/fonts/[name]-[hash][extname]' : 'assets/[name]-[hash][extname]'
        },
        manualChunks(id) {
          const pkg = npmPackageOf(id)
          if (pkg === undefined) return undefined
          if (pkg === '@shikijs/langs') {
            return BOOT_GRAMMAR_FILES.some(file => id.endsWith(`/${file}`)) ? 'vendor' : undefined
          }
          return VENDOR_PACKAGES.has(pkg) ? 'vendor' : undefined
        },
      },
    },
    // P2-4 (STATUS): renderer output is isolated under dist/web so a
    // standalone `build:renderer` can never wipe sibling desktop artifacts
    // (preload.cjs / control-plane / host packages) that share dist/.
    outDir: '../desktop/dist/web',
    emptyOutDir: true,
  },
  resolve: {
    alias: [
      // Browserization of the vendored cordis Loader: its only node-only import.
      { find: /^node:module$/, replacement: src('./src/node-module-stub.ts') },
      // The chamber self-built sidebar plugin resolves to source (design 05
      // §2); deepseekSource covers the @deepseek-ai/* tree, this is the
      // @dsh-chamber/* row. The renderer imports only /client (boot graph)
      // and /shared (chamberBridge + instance unary client); the bare spec
      // maps to the host no-op entry for completeness.
      { find: /^@dsh-chamber\/dsh-client-ui-sidebar$/, replacement: src('../dsh-chamber-client-ui-sidebar/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-sidebar\/client$/, replacement: src('../dsh-chamber-client-ui-sidebar/src/client/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-sidebar\/shared$/, replacement: src('../dsh-chamber-client-ui-sidebar/src/shared/index.ts') },
      // Chamber Git worktree occupant: static first-screen client + shared
      // coordinator/API helpers. It depends on the sidebar's neutral shared
      // bridge, never on an App-owned Git aggregate.
      { find: /^@dsh-chamber\/dsh-client-ui-git$/, replacement: src('../dsh-chamber-client-ui-git/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-git\/client$/, replacement: src('../dsh-chamber-client-ui-git/src/client/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-git\/shared$/, replacement: src('../dsh-chamber-client-ui-git/src/shared/index.ts') },
      // Chamber open-in header button (design 16 + open-in extension): static
      // first-screen client; the coordinator reads the main-process app list
      // through the preload bridge (zero @dsh-chamber dependencies).
      { find: /^@dsh-chamber\/dsh-client-ui-open-in$/, replacement: src('../dsh-chamber-client-ui-open-in/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-open-in\/client$/, replacement: src('../dsh-chamber-client-ui-open-in/src/client/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-open-in\/shared$/, replacement: src('../dsh-chamber-client-ui-open-in/src/shared/index.ts') },
      // The chamber-owned ui-layout fork (design 06) resolves to source the
      // same way: it replaces the official layout in the boot graph, and its
      // client imports the vendor frame through `@deepseek-ai/.../src/*` deep
      // subpaths (deepseekSource resolves those). The renderer imports only
      // /client; the bare spec maps to the host no-op entry for completeness.
      { find: /^@dsh-chamber\/dsh-client-ui-layout$/, replacement: src('../dsh-chamber-client-ui-layout/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-layout\/client$/, replacement: src('../dsh-chamber-client-ui-layout/src/client/index.ts') },
      // The chamber self-built connections settings section plugin (design
      // 05 §5) resolves to source the same way.
      { find: /^@dsh-chamber\/dsh-client-ui-settings-connections$/, replacement: src('../dsh-chamber-client-ui-settings-connections/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-settings-connections\/client$/, replacement: src('../dsh-chamber-client-ui-settings-connections/src/client/index.ts') },
      // The chamber self-built settings SHELL plugin (design discussion
      // 2026-08) resolves to source the same way.
      { find: /^@dsh-chamber\/dsh-client-ui-settings-bridge$/, replacement: src('../dsh-chamber-client-ui-settings-bridge/src/index.ts') },
      { find: /^@dsh-chamber\/dsh-client-ui-settings-bridge\/client$/, replacement: src('../dsh-chamber-client-ui-settings-bridge/src/client/index.ts') },
      // The settings shell embeds the connections section component directly
      // (stable `./section` exports subpath — A6; explicit alias so the
      // resolution does not ride the generic npm fallback).
      { find: /^@dsh-chamber\/dsh-client-ui-settings-connections\/section$/, replacement: src('../dsh-chamber-client-ui-settings-connections/src/client/ConnectionsSection.tsx') },
      // CSS `@import` of workspace stylesheets bypasses the resolveId plugin
      // container (vite's back-compat CSS resolver runs alias + node
      // resolution only), and the packages' `./styles` export points at the
      // BUILT lib/ tree the source-only vendor cannot provide. Map the
      // subpath straight into the vendor source tree.
      { find: /^@deepseek-ai\/([^/]+)\/styles\//, replacement: src('../../vendor/harness-packages/@deepseek-ai/$1/src/styles/') },
    ],
  },
  define: {
    'process.versions.node': '"0.0.0"',
    'process.execArgv': '[]',
    'process.env.CORDIS_SHARED': 'undefined',
    // rc.8 (design 09 §4): ui-brand-official gates its official brand fills on
    // `DSH_CLIENT_BUILD_PROFILE === 'official'` ("other builds load the plugin
    // but register no occupants" — the package contract). The chamber
    // self-build is not the official profile: define it away so the gate
    // constant-folds to a clean no-op — without the define the browser would
    // throw `process is not defined` inside the deferred apply on every boot.
    'process.env.DSH_CLIENT_BUILD_PROFILE': JSON.stringify('chamber'),
  },
})
